### ISSUE TITLE
Could not import gpt4all library. Please install the gpt4all library to use this embedding model: pip install gpt4all

### ISSUE THREAD

**Issue by fruedaCode** [Nagi-ovo/CRAG-Ollama-Chat#2]
Hello

I just run streamlit run app.py and I'm getting this error:
Could not import gpt4all library. Please install the gpt4all library to use this embedding model: pip install gpt4all

I'm using python 3.11.8 and this is the configuration I applied:
```yml
# APIs
openai_api_key: "" # Not necessary if run_local is true
openai_api_base: "https://api.openai.com/v1/chat/completions" # or your own proxy
google_api_key: "" # Not necessary if run_local is true
tavily_api_key: ""

# Ollama Config
run_local: "Yes" # must have ollama runnig in ur PC if Yes
local_llm: "mistral" # mistral, llama2 ...

# Model Config
models: "openai" # Not necessary if run_local is true

# Document Config
doc_url:
  - "https://personalurl.com"
```

Should I include gpt4all in requirements.txt?
